
GET http://localhost:4000?username=sakil

###

POST http://localhost:4000
Content-Type: application/json

{
  "name": "Sakil Bro"

}

###

POST http://localhost:4000
Content-Type: application/json

{
  "name": "sakil",
  "email": "sakil123@gmail.com",
  "password": "afdUfxxcs324df#",
  "confirmPassword": "afdUfxxcs324df#",
  "bio": "some dummy text as bio",
  "addresses": [
    {
      "city": "Bhanga",
      "postcode": "7830"
    },
    {
      "city": "Faridpur",      "postcode": 7800
    }
  ],
  "skills": "Javascript, Typescript, React, Node"
}